# Generated by Django 5.1.1 on 2024-10-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_agendaitem_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaitem',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
